// src/MicrosoftEntraIdDemoApp/UI/Angular/microsoft-entra-demo-app/src/app/auth-test/auth-test.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { AuthTestServiceTsService } from './auth-test.service.ts.service';
import { ActivatedRoute } from '@angular/router';
import { lastValueFrom, Subscription } from 'rxjs';

@Component({
  selector: 'app-auth-test',
  imports: [],
  templateUrl: './auth-test.component.html',
  styleUrl: './auth-test.component.scss'
})
export class AuthTestComponent implements OnInit, OnDestroy {

  public message: string | null = null;

  private routerChangeSubscription: Subscription | null = null;

  constructor(
    private readonly authTestService: AuthTestServiceTsService,
    private readonly route: ActivatedRoute
  ) { }

  /**
   * On component initialization, we check the route parameters for a 'type' and call the appropriate API endpoint using the AuthTestService. We also handle any errors that may occur during the API call and display an appropriate message to the user.
   */
  async ngOnInit(): Promise<void> {
    this.routerChangeSubscription = this.route.params.subscribe(async () => {
      await this.loadData();
    });
  }

  ngOnDestroy(): void {
    this.routerChangeSubscription?.unsubscribe();
  }

  /**
   * Load data from api based on the 'type' route parameter. If the 'type' parameter is not valid, it defaults to 'no_available_type'. The result from the API call is then displayed to the user, and any errors are caught and displayed as well.
   */
  private async loadData() {
    const type = this.checkIfTypeExists(this.route.snapshot.paramMap.get('type') || 'empty');

    this.message = `Testing ${type} endpoint...`;
    try {
      const result = await lastValueFrom(this.authTestService.getData(type));
      this.message = result.message;
    }
    catch (error) {
      this.message = error instanceof Error ? error.message : 'An unknown error occurred.';
    }
  }

  /**
   * Checks if the provided type exists in the list of valid types.
   * @param type the type to check
   * @returns the valid type if it exists, otherwise 'no_available_type'
   */
  private checkIfTypeExists(type: string): string {
    const validTypes = ['checkGroup', 'apptesters', 'test', 'admin'];

    if (validTypes.includes(type)) {
      return type;
    } else {
      return 'no_available_type';
    }
  }
}

@if (message) {
  <p>{{ message }}</p>
} @else {
  <p>Loading...</p>
}

// src/MicrosoftEntraIdDemoApp/UI/React/microsoft-entra-demo-app/src/auth-test/auth-test.component.tsx
import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { getData } from "./auth-test.service";

/**
 * Checks if the provided type exists in the list of valid types.
 * @param type the type to check
 * @returns the valid type if it exists, otherwise 'no_available_type'
 */
const checkIfTypeExists = (type: string): string => {
  const validTypes = ["checkGroup", "apptesters", "test", "admin"];

  if (validTypes.includes(type)) {
    return type;
  } else {
    return "no_available_type";
  }
};

export default function AuthTestComponent() {
  const { type } = useParams<{ type: string }>();
  const [message, setMessage] = useState("Loading...");

  useEffect(() => {
    const fetchUser = async () => {
      try {
        const validType = checkIfTypeExists(type || "");

        const response = await getData(validType);
        setMessage(response?.message ?? "No message");
      } catch (error) {
        if (error instanceof Error) {
          setMessage(`Error: ${error.message}`);
        } else {
          setMessage("Error fetching user");
        }
      }
    };

    fetchUser();
  }, [type]); // Reaguje na zmianę parametru type

  return <p>{message}</p>;
}
